autocli/urls.py
# Django Import:
from django.urls import path, include
from django.contrib import admin

# Admin URL pattern:
urlpatterns = [
    path('admin/', admin.site.urls),
    path('inventory/', include('inventory.urls')),
]

inventory/urls.py
# Django Import:
from django.urls import path

# Application Import:
from inventory.views.test_view import automation, logger_page, test_all_devices_view, test_single_devices_view

app_name = 'inventory'

urlpatterns = [
    path('test', automation, name='inventory'),
    path('logger', logger_page, name='logger'),
    path('devices', test_all_devices_view, name='device_all'),
    path('device/<str:pk>', test_single_devices_view, name='device_one'),
]

automation/views/test_view.py
# Django Import:
from django.shortcuts import render

# Application Import:
from logger.logger import Logger

# Task Import:
from automation.task import test_task
from automation.tasks.collect_device_data import collect_device_data

# Models Import:
from inventory.models.device_collected_data_model import DeviceCollectedData

# Logger initialization:
logger = Logger('Page')

def automation(request):

    logger.info('------------------------------------')

    # Collect data to display:
    data = {
        'output': 'Test RKKR',
        'log': '',
    }

    # data['output'] = test_task.delay([True, False])
    data['output'] = collect_device_data(1)
    
    # GET method:
    return render(request, 'basic.html', data)

inventory/views/test_view.py
# Django Import:
from django.shortcuts import render
import threading

# Application Import:
from logger.logger import Logger
from django.db import IntegrityError

# Task Import:
from inventory.models.device_type_template_model import DeviceTypeTemplate
from inventory.tasks.old.collect_device_data import collect_device_data, collect_all_devices_data
from inventory.connections.netcon import NetCon
from inventory.connections.apicon import ApiCon
from inventory.tasks.collect_device_data_task import CollectDeviceDataTask
from inventory.tasks.check_device_status_task import CheckDeviceStatus
from inventory.models.device_collected_data_model import DeviceCollectedData
from inventory.models.device_update_model import DeviceUpdate
from inventory.models.device_model import Device

from django.core.exceptions import ValidationError

# Logger initialization:
logger = Logger('Page')

def test_all_devices_view(request):
    data = {
        'output': 'All devices view',
    }

    devices = Device.objects.all()

    data['devices'] = devices
    return render(request, 'test_all_devices_view.html', data)

def test_single_devices_view(request, pk):
    data = {
        'output': 'Single device view',
    }

    devices = Device.objects.all()
    data['devices'] = devices
    device = Device.objects.get(pk=pk)
    data['device'] = device
    data['output'] = device.name

    updates = DeviceUpdate.objects.filter(device=device)
    data['updates'] = updates
    last_update = DeviceUpdate.objects.filter(device=device).latest('updated')
    data['last_update'] = last_update

    all_collected_data = DeviceCollectedData.objects.filter(device_update=last_update)
    data['all_collected_data'] = all_collected_data

    return render(request, 'test_single_devices_view.html', data)

def logger_page(request):
    data = {
        'output': 'Log page',
        'log': '',
    }

    device = Device.objects.get(pk=1)


    # data['output'] = CollectDeviceDataTask.delay(1)

    # device = Device.objects.get(pk=1)
    # connection = ApiCon(device)
    # url = 'restconf/data/Cisco-IOS-XE-native:native/hostname'
    # data['output'] = connection.get(url)

    # logger.info('aaa')
    # logger.info('bbb')
    # logger.info('ccc')
    # logger.info('ddd')
    # logger.info('eee')
    return render(request, 'test.html', data)


def check_device_activity(device):
    ssh_connection = NetCon(device, repeat_connection=1).test_connection()
    if ssh_connection:
        device.ssh_status = True
    else:
        device.ssh_status = False
    device.save(update_fields=['ssh_status'])



def automation(request):

    # Collect data to display:
    data = {
        'output': 'Test RKKR',
        'log': '',
    }
    logger.info('XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX')
    data['output'] = CollectDeviceDataTask.delay('all')
    # data['output'] = CheckDeviceStatus.delay('all')
    


    
    
    # output = []
    # threads = list()
    # devices = Device.objects.filter(active=True)
    
    # for device in devices:
    #     thread = threading.Thread(target=check_device_activity, args=(device,))
    #     threads.append(thread)
    #     thread.start()

    # for index, thread in enumerate(threads):
    #     thread.join()
        
    # data['output'] = output







    # data['output'] = collect_all_devices_data.delay()
    # data['output'] = collect_last_logs.delay()

    # data['output'] = test_task.delay([True, False])
    # data['output'] = collect_device_data(1)

    # try:
    #     data['output'] = Device.objects.get(pk=1)
    # except IntegrityError as error:
    #     data['output'] = error

    # device = Device.objects.get(pk=1)
    # connection = NetCon(device).open_connection()
    # # data['output'] = connection.enabled_commands(['show version', 'show interfaces', 'show interfaces switchport', 'show ip interface', 'show cdp neighbors', 'show clock', 'show access-list', 'show ip access-list', 'show ip route', 'show inventory', 'show vrf'])
    # if connection:
    #     # data['output'] = connection.enabled_commands(['show access-list', 'show ip access-list'])
    #     # template = DeviceTypeTemplate.objects.get(pk=1)
    #     # data['output'] = connection.enabled_commands(fsm_template_object=template)
    #     # data['output'] = collect_device_data(1)
    #     # data['output'] = connection.execute_device_type_templates()
    #     connection.close_connection()
    
    # GET method:
    return render(request, 'test.html', data)

templates/base.html
{% load i18n %}
{% load static %}

<!DOCTYPE html>

<html lang="{{ LANGUAGE_CODE }}">

    <head>

        <!-- Page basic data -->
        <meta charset="UTF-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        
        <!-- Page title -->
        <title>AutoCli - base</title>
        
        <!-- Custom CSS -->
        <link rel="stylesheet" type="text/css" href="{% static 'css/reset.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'css/base.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'css/content.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'css/mobile.css' %}">

        <!-- Icons -->
        <script src="https://kit.fontawesome.com/f8557c5cb5.js" crossorigin="anonymous"></script>

        <!-- Favicon links -->
        <link rel="apple-touch-icon" sizes="180x180" href="{% static 'ico/favicon/apple-touch-icon.png' %}">
        <link rel="icon" type="image/png" sizes="32x32" href="{% static 'ico/favicon/favicon-32x32.png' %}">
        <link rel="icon" type="image/png" sizes="16x16" href="{% static 'ico/favicon/favicon-16x16.png' %}">
        <link rel="manifest" href="{% static 'ico/favicon/site.webmanifest' %}">
        <link rel="mask-icon" href="{% static 'ico/favicon/safari-pinned-tab.svg' %}" color="#5bbad5">
        <meta name="msapplication-TileColor" content="#da532c">
        <meta name="theme-color" content="#ffffff">
        
    </head>

    <body>
        
        <!-- Main div containing all page content. -->
        <div id="page">

            <!-- Top site of page. -->
            <div id="page_top">

                <!-- xxx -->
                <div id="page_left_logo">
                    <p>page_left_logo</p>
                </div>

                <!-- xxx -->
                <div id="page_top_menu">

                    <!-- xxx -->
                    <div id="page_top_action">
                        <p>page_top_action</p>
                    </div>

                    <!-- xxx -->
                    <div id="page_top_name">
                        <p>page_top_name</p>
                    </div>

                    <!-- xxx -->
                    <div id="page_top_user">
                        <p>page_top_user</p>
                    </div>

                </div>

            </div>

            <!-- Bottom site of page. -->
            <div id="page_bottom">

                <!-- Left site of page (Left menu). -->
                <div id="page_left">

                    <!-- xxx -->
                    <div id="page_left_top">

                        <!-- xxx -->
                        <div id="page_left_menu">
                            
                            <nav id="main_menu">

                                <!-- Menu item -->
                                <li class="menu_item">
                                    <a href="#" class="menu_link">
                                        <span class="menu_link_svg">
                                            <i class="fa-solid fa-house-chimney"></i>
                                        </span>
                                        <span class="menu_link_text">{% translate "Dashboard" %}</span>
                                    </a>
                                </li>

                                <!-- Menu item -->
                                <li class="menu_item">
                                    <a href="#" class="menu_link">
                                        <span class="menu_link_svg">
                                            <i class="fa-solid fa-address-card"></i>
                                        </span>
                                        <span class="menu_link_text">{% translate "Administration" %}</span>
                                    </a>
                                </li>

                                <!-- Menu item -->
                                <li class="menu_item menu_collapse">
                                    <p class="menu_link menu_collapse_link">
                                        <span class="menu_link_svg">
                                            <i class="fa-solid fa-cart-flatbed"></i>
                                        </span>
                                        <span class="menu_link_text">{% translate "Inventory" %}</span>
                                    </p>
                                    <ul class="submenu collapse">

                                        <li class="menu_item">
                                            <a href="#"  class="menu_link">
                                                <span class="menu_link_svg">
                                                    <i class="fa-solid fa-arrow-right"></i>
                                                </span>
                                                <span class="menu_link_text">{% translate "Devices" %}</span>
                                            </a>
                                        </li>

                                        <li class="menu_item">
                                            <a href="#"  class="menu_link">
                                                <span class="menu_link_svg">
                                                    <i class="fa-solid fa-arrow-right"></i>
                                                </span>
                                                <span class="menu_link_text">{% translate "Groups" %}</span>
                                            </a>
                                        </li>

                                        <li class="menu_item">
                                            <a href="#"  class="menu_link">
                                                <span class="menu_link_svg">
                                                    <i class="fa-solid fa-arrow-right"></i>
                                                </span>
                                                <span class="menu_link_text">{% translate "Colors" %}</span>
                                            </a>
                                        </li>

                                        <li class="menu_item">
                                            <a href="#"  class="menu_link">
                                                <span class="menu_link_svg">
                                                    <i class="fa-solid fa-arrow-right"></i>
                                                </span>
                                                <span class="menu_link_text">{% translate "Credentials" %}</span>
                                            </a>
                                        </li>

                                    </ul>
                                </li>

                                <!-- Menu item -->
                                <li class="menu_item menu_collapse">
                                    <p class="menu_link menu_collapse_link">
                                        <span class="menu_link_svg">
                                            <i class="fa-solid fa-gears"></i>
                                        </span>
                                        <span class="menu_link_text">{% translate "Automatization" %}</span>
                                    </p>
                                    <ul class="submenu collapse">

                                        <li class="menu_item">
                                            <a href="#"  class="menu_link">
                                                <span class="menu_link_svg">
                                                    <i class="fa-solid fa-arrow-right"></i>
                                                </span>
                                                <span class="menu_link_text">{% translate "Polices" %}</span>
                                            </a>
                                        </li>

                                        <li class="menu_item">
                                            <a href="#"  class="menu_link">
                                                <span class="menu_link_svg">
                                                    <i class="fa-solid fa-arrow-right"></i>
                                                </span>
                                                <span class="menu_link_text">{% translate "Templates" %}</span>
                                            </a>
                                        </li>

                                        <li class="menu_item">
                                            <a href="#"  class="menu_link">
                                                <span class="menu_link_svg">
                                                    <i class="fa-solid fa-arrow-right"></i>
                                                </span>
                                                <span class="menu_link_text">{% translate "Schedules" %}</span>
                                            </a>
                                        </li>

                                    </ul>
                                </li>

                                <!-- Menu item -->
                                <li class="menu_item">
                                    <a href="#" class="menu_link">
                                        <span class="menu_link_svg">
                                            <i class="fa-solid fa-sliders"></i>
                                        </span>
                                        <span class="menu_link_text">{% translate "Settings" %}</span>
                                    </a>
                                </li>

                            </nav>

                        </div>

                    </div>

                    <!-- xxx -->
                    <div id="page_left_options">
                    </div>

                </div>

                <!-- All right site of page (Top panel and main page content). -->
                <div id="page_right">

                    <!-- main page content. -->
                    <div id="page_content">

                        <!-- xxx -->
                        <div id="content">

                            {% block content %}{% endblock content %}

                        </div>

                    </div>

                </div>

            </div>


        </div>

        <!-- JavaScript scripts -->
        <script src="{% static 'js/base_main.js' %}"></script>
        <script src="{% static 'js/websocket.js' %}"></script>
        
    </body>

</html>

templates/basic.html
{% load i18n %}
{% load static %}

<!DOCTYPE html>

<html lang="{{ LANGUAGE_CODE }}">

    <head>

        <!-- Page basic data -->
        <meta charset="UTF-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        
        <!-- Page title -->
        <title>AutoCli - base</title>
        
        <!-- Custom CSS -->
        <link rel="stylesheet" type="text/css" href="{% static 'css/reset.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'css/base.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'css/content.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'css/mobile.css' %}">

        <!-- Icons -->
        <script src="https://kit.fontawesome.com/f8557c5cb5.js" crossorigin="anonymous"></script>

        <!-- Favicon links -->
        <link rel="apple-touch-icon" sizes="180x180" href="{% static 'ico/favicon/apple-touch-icon.png' %}">
        <link rel="icon" type="image/png" sizes="32x32" href="{% static 'ico/favicon/favicon-32x32.png' %}">
        <link rel="icon" type="image/png" sizes="16x16" href="{% static 'ico/favicon/favicon-16x16.png' %}">
        <link rel="manifest" href="{% static 'ico/favicon/site.webmanifest' %}">
        <link rel="mask-icon" href="{% static 'ico/favicon/safari-pinned-tab.svg' %}" color="#5bbad5">
        <meta name="msapplication-TileColor" content="#da532c">
        <meta name="theme-color" content="#ffffff">
        
    </head>

    <body>
        
        <!-- Main div containing all page content. -->
        <div id="page">

            <!-- Top site of page. -->
            <div id="page_top">

                <!-- xxx -->
                <div id="page_left_logo">
                    <p>page_left_logo</p>
                </div>

                <!-- xxx -->
                <div id="page_top_menu">

                    <!-- xxx -->
                    <div id="page_top_action">
                        <p>page_top_action</p>
                    </div>

                    <!-- xxx -->
                    <div id="page_top_name">
                        <p>page_top_name</p>
                    </div>

                    <!-- xxx -->
                    <div id="page_top_user">
                        <p>page_top_user</p>
                    </div>

                </div>

            </div>

            <!-- Bottom site of page. -->
            <div id="page_bottom">

                <!-- Left site of page (Left menu). -->
                <div id="page_left">

                    <!-- xxx -->
                    <div id="page_left_top">

                        <!-- xxx -->
                        <div id="page_left_menu">
                            
                            <nav id="main_menu">

                                <!-- Menu item -->
                                <li class="menu_item">
                                    <a href="#" class="menu_link">
                                        <span class="menu_link_svg">
                                            <i class="fa-solid fa-house-chimney"></i>
                                        </span>
                                        <span class="menu_link_text">{% translate "Dashboard" %}</span>
                                    </a>
                                </li>

                                <!-- Menu item -->
                                <li class="menu_item">
                                    <a href="#" class="menu_link">
                                        <span class="menu_link_svg">
                                            <i class="fa-solid fa-address-card"></i>
                                        </span>
                                        <span class="menu_link_text">{% translate "Administration" %}</span>
                                    </a>
                                </li>

                                <!-- Menu item -->
                                <li class="menu_item menu_collapse">
                                    <p class="menu_link menu_collapse_link">
                                        <span class="menu_link_svg">
                                            <i class="fa-solid fa-cart-flatbed"></i>
                                        </span>
                                        <span class="menu_link_text">{% translate "Inventory" %}</span>
                                    </p>
                                    <ul class="submenu collapse">

                                        <li class="menu_item">
                                            <a href="#"  class="menu_link">
                                                <span class="menu_link_svg">
                                                    <i class="fa-solid fa-arrow-right"></i>
                                                </span>
                                                <span class="menu_link_text">{% translate "Devices" %}</span>
                                            </a>
                                        </li>

                                        <li class="menu_item">
                                            <a href="#"  class="menu_link">
                                                <span class="menu_link_svg">
                                                    <i class="fa-solid fa-arrow-right"></i>
                                                </span>
                                                <span class="menu_link_text">{% translate "Groups" %}</span>
                                            </a>
                                        </li>

                                        <li class="menu_item">
                                            <a href="#"  class="menu_link">
                                                <span class="menu_link_svg">
                                                    <i class="fa-solid fa-arrow-right"></i>
                                                </span>
                                                <span class="menu_link_text">{% translate "Colors" %}</span>
                                            </a>
                                        </li>

                                        <li class="menu_item">
                                            <a href="#"  class="menu_link">
                                                <span class="menu_link_svg">
                                                    <i class="fa-solid fa-arrow-right"></i>
                                                </span>
                                                <span class="menu_link_text">{% translate "Credentials" %}</span>
                                            </a>
                                        </li>

                                    </ul>
                                </li>

                                <!-- Menu item -->
                                <li class="menu_item menu_collapse">
                                    <p class="menu_link menu_collapse_link">
                                        <span class="menu_link_svg">
                                            <i class="fa-solid fa-gears"></i>
                                        </span>
                                        <span class="menu_link_text">{% translate "Automatization" %}</span>
                                    </p>
                                    <ul class="submenu collapse">

                                        <li class="menu_item">
                                            <a href="#"  class="menu_link">
                                                <span class="menu_link_svg">
                                                    <i class="fa-solid fa-arrow-right"></i>
                                                </span>
                                                <span class="menu_link_text">{% translate "Polices" %}</span>
                                            </a>
                                        </li>

                                        <li class="menu_item">
                                            <a href="#"  class="menu_link">
                                                <span class="menu_link_svg">
                                                    <i class="fa-solid fa-arrow-right"></i>
                                                </span>
                                                <span class="menu_link_text">{% translate "Templates" %}</span>
                                            </a>
                                        </li>

                                        <li class="menu_item">
                                            <a href="#"  class="menu_link">
                                                <span class="menu_link_svg">
                                                    <i class="fa-solid fa-arrow-right"></i>
                                                </span>
                                                <span class="menu_link_text">{% translate "Schedules" %}</span>
                                            </a>
                                        </li>

                                    </ul>
                                </li>

                                <!-- Menu item -->
                                <li class="menu_item">
                                    <a href="#" class="menu_link">
                                        <span class="menu_link_svg">
                                            <i class="fa-solid fa-sliders"></i>
                                        </span>
                                        <span class="menu_link_text">{% translate "Settings" %}</span>
                                    </a>
                                </li>

                            </nav>

                        </div>

                    </div>

                    <!-- xxx -->
                    <div id="page_left_options">
                        <p>page_left_options</p>
                    </div>

                </div>

                <!-- All right site of page (Top panel and main page content). -->
                <div id="page_right">

                    <!-- main page content. -->
                    <div id="page_content">

                        <!-- xxx -->
                        <div id="content">

                            {{ output }}
                            </br></br></br></br></br></br>
                            {{ output2 }}
                    
                            <p>Collect output</p>
                            <p id="collect_output"></p>
                    
                            <p>Logger output</p>
                            <div id="logger_output"></div>

                        </div>

                    </div>

                </div>

            </div>


        </div>

        <!-- JavaScript scripts -->
        <script src="{% static 'js/base_main.js' %}"></script>
        
    </body>

</html>

templates/test.html
{% extends "base.html" %}
{% load i18n %}
{% load static %}

{% block content %}

    {{ output }}
    </br></br></br></br></br></br>
    {{ output2 }}

    <p>Collect output</p>
    <p id="collect_output"></p>

    <p>Logger output</p>
    <div id="logger_output"></div>

{% endblock %}

templates/test_all_devices_view.html
{% extends "base.html" %}
{% load i18n %}
{% load static %}

{% block content %}

    <h3>{{ output }}</h3>
    </br>
    <p>-----------------------</p>
    </br>
    {% for device in devices %}

        <li><a href="{% url 'inventory:device_one' device.pk %}">{{ device.name }}</a> - {{ device.hostname }}</li>

    {% endfor %}

{% endblock %}

templates/test_single_devices_view.html
{% extends "base.html" %}
{% load i18n %}
{% load static %}

{% block content %}

    <h3>{{ output }}</h3>
    <p>-----------------------</p>
    </br>

    <li><strong>Hostname:</strong> {{ device.hostname }}</li>
    <li><strong>SSH port:</strong> {{ device.ssh_port }}</li>
    <li><strong>HTTPS port:</strong> {{ device.https_port }}</li>
    <li><strong>Device type:</strong> {{ device.device_type }}</li>
    <li><strong>SSH status:</strong> {{ device.ssh_status }}</li>
    <li><strong>HTTPS status:</strong> {{ device.https_status }}</li>
    <li><strong>Credential:</strong> {{ device.credential }}</li>
    
    </br>
    <h3>Updates</h3>
    <p>-----------------------</p>
    </br>

    {% for update in updates %}

        <li>{{ update.created }} - {{ update.status }} {{ update.result_status }}</li>

    {% endfor %}
    
    </br>
    <h3>All collected data</h3>
    <p>-----------------------</p>
    </br>

    {% for data in all_collected_data %}

        <li>{{ data.command_name }} - {{ data.result_status }} - {{ data.raw_data_status }} {{ data.processed_data_status }}</li>

    {% endfor %}
    
    </br>
    <h3>All devices:</h3>
    <p>-----------------------</p>
    </br>
    {% for device in devices %}

        <li><a href="{% url 'inventory:device_one' device.pk %}">{{ device.name }}</a> - {{ device.hostname }}</li>

    {% endfor %}

{% endblock %}